version: '3.8'

services:
  db:
    container_name: user-service-demo
    image: postgres
    restart: always
    networks:
      - userservice
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: o1m3r4i7
      POSTGRES_DB: users
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    networks:
      - userservice
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

networks:
  userservice: